project:
  type: website

website:
  title: "StatOmique"
  
  navbar:
    logo: media/LOGO-GDR_BIMMM.png
    left:
 
      - href: index.qmd
        text: "Accueil"
      - href: animations.qmd  
      - communaute.qmd  
      - communications.qmd
      - href: apropos.qmd
        text: "Organisation"
        
format:
  html:
    theme: 
     light: flatly
     dark: darkly
    css: styles.css
    toc: true

editor: visual


